### PR TITLE
Show dynamic dates #33

### PR DESCRIPTION
**Pull request by devyaniChoubey**

### CODE REVIEW

**Comment by thebishaldeb** [comment]
Some screenshots please.

**Comment by devyaniChoubey** [comment]
Screenshot (26)

**Comment by devyaniChoubey** [comment]
@thebishaldeb data format is like "27-november-2000"

**Comment by devyaniChoubey** [comment]
As you have told, If the number of days will be less than 8 it will show no. of days else it will show the date of submission for both comments as well as blogs

**Comment by thebishaldeb** [comment]
Merged it, but change the  moth to only three letters like Jan, Feb, etc in the next PR.

**Pull request merged**
