### PR TITLE
Increase the form in registration page #7

### PR DESCRIPTION
**Pull request by devyaniChoubey**

### CODE REVIEW

**Comment by devyaniChoubey** [comment]
Screenshot (12)
Screenshot (13)

**Comment by devyaniChoubey** [comment]
@thebishaldeb  I have made changes to edit comment page also and It will fix the issue #24 .

**Comment by thebishaldeb** [comment]
Does it get saved in the database? I mean, have you checked if it works in the backend as well? 

I don't know the details of the issue there in #24 yet and have not labelled it. So it can only be solved after it is labelled.

**Comment by devyaniChoubey** [comment]
@thebishaldeb  now it is getting saved t db actually i forgot to make these changes.
Screenshot (15)

**Pull request merged**
