### PR TITLE
Dislike and like button added

### PR DESCRIPTION
**Pull request by anushkamittal**

### CODE REVIEW

**Comment by thebishaldeb** [comment]
Some screenshots of the same, please.

**Comment by anushkamittal** [comment]
Screenshot from 2019-12-15 14-26-41
Screenshot from 2019-12-15 14-26-51

**Comment by thebishaldeb** [comment]
Use thumb icons (or whatever fits in there) for the same and aligned in the same line. And make sure a person cannot perform both the actions for the same post. And also do it just once with the option to undo it. Undoing deletes the data.

Also rather than creating two schemas, one for like and another for dislike, make one, with some text / flag field like 1 / 'like' for like and -1 / 'dislike' for dislike, so that a person can just toggle between the two.

**Comment by thebishaldeb** [comment]
@anushkamittal made those changes requested?

**Comment by anushkamittal** [comment]
I have converted it into one schema. Working on it further.

**Comment by anushkamittal** [comment]
@thebishaldeb please review it now

**Comment by thebishaldeb** [comment]
Conflicting files need to be resolved.

Also upload screenshots of the page worked on.

**Comment by anushkamittal** [comment]
Screenshot from 2019-12-21 17-59-53

**Comment by anushkamittal** [comment]
Screenshot from 2019-12-21 17-59-53

**Pull request merged**
