### PR TITLE
update readme.md file

### PR DESCRIPTION
**Pull request by sgpritam**
issue #23

### CODE REVIEW

**Comment by sgpritam** [comment]
@thebishaldeb Please review

**Comment by sgpritam** [comment]
Before changes:-
image

image

After changes :- 
image

**Comment by thebishaldeb** [comment]
THe images need to be updated too. The login page, registration page, comments page (actually all the pagrs currently there) need to be present in the readme in small size and with proper heading.

**Comment by sgpritam** [comment]
@thebishaldeb Please review

**Comment by thebishaldeb** [comment]
The headings are wrong. Please check them out. The add, edit comments, registration and login page are different. Also there had been style changes since the prev pictures in the readme. So include the new ones.

You might consider adding a GIF instead too, instead of all the pictures.

**Comment by sgpritam** [comment]
Please tell me explain heading of image

**Comment by thebishaldeb** [comment]
You wrote the landing page as login page which is not. Also registration page isn't that. 
Those are the ones having forms.

**Comment by sgpritam** [comment]
@thebishaldeb Please check

**Comment by thebishaldeb** [comment]
It is still wrong. If you logout, then the page you see for loging in is the login page, similarly the registration page. Also if you click on add comment, you will see the add comments page, similarly edit comments page.
If you click on add new instances, that is add event page, similarly edit event.

**Pull request closed without merging**
