### PR TITLE
added location feature

### PR DESCRIPTION
**Pull request by ankushbhardwxj**
Added the required location feature to display the location while creating the blog.
dome

### CODE REVIEW

**Comment by ankushbhardwxj** [comment]
@thebishaldeb please review

**Comment by thebishaldeb** [comment]
Resolve conflicts

**Comment by ankushbhardwxj** [comment]
@thebishaldeb done 👍

**Comment by ankingcodes** [comment]
@thebishaldeb why does these conflicts occur ??

**Pull request merged**
